# Author : Akash Sisodiya
service: api-get-current-time
provider:
  name: aws
  runtime: nodejs10.x
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: time
          method: get