# Author: Akash Sisodiya
service: api-get-random-number

provider:
  name: aws
  runtime: nodejs10.x

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: randomnumber
          method: get